Require setuptools
setuptools are a runtime requirement, without them
```
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```